### PR TITLE
fix: support `rliger` versions < 2.0 and >= 2.0

### LINKED ISSUE #219: Review: Update for LIGER batch correction
Manual test of LIGER with latest version of Seurat is failing due to Seurat reclassifying `assay` to `layer`. LIGER has an update as well: https://welch-lab.github.io/liger/articles/liger_with_seurat.html

Will need to run a thorough test of the batch correction workflow to ensure up-to-date compatibility.

### PR DESCRIPTION
**Pull request by wong-nw**
## Changes

Updates code to reflect changes from updates to `rliger`, as required for the updated container

- Builds a catch in the `MAIN_BATCH_CORRECTION` function to use correct code and function calls
- Secondary catch in `batch_correction_liger.Rmd` to ensure that the appropriate label for dimensional reduction is referenced in downstream steps

## Issues

Fixes #219 

## PR Checklist

(~Strikethrough~ any points that are not applicable.)

- [x] This comment contains a description of changes with justifications, with any relevant issues linked.
- ~[ ] Write tests using [`nf-test`](https://www.nf-test.com/) for any new features, bug fixes, or other code changes.~
- ~[ ] Update docs if there are any API changes.~
- ~[ ] If a new nextflow process is implemented, define the process `container` and `stub`.~
- [x] Update `CHANGELOG.md` with a short description of any user-facing changes and reference the PR number. Guidelines: https://keepachangelog.com/en/1.1.0/

### CODE REVIEW

File: bin/scRNA_functions.R [hunk 1]
```diff
@@ -250,13 +250,21 @@ MAIN_BATCH_CORRECTION <- function(
...
+      so_norm <- Seurat::ScaleData(so_norm, do.center = FALSE)
+      so_norm <- Seurat::RunOptimizeALS(so_norm, k = npcs, lambda = 5)
+      so_integrate <- Seurat::RunQuantileNorm(so_norm)
+    } else {
+      so_norm <- rliger::normalize(so_in)
+      so_norm <- rliger::selectGenes(so_norm)
+      so_norm <- rliger::scaleNotCenter(so_norm)
+      so_norm <- rliger::runINMF(so_norm, k = npcs)
+      so_integrate <- rliger::quantileNorm(so_norm)
+    }
```
Comment (kelly-sovacool) [inline bin/scRNA_functions.R:267]: since can control the version of rliger, why not get rid of the conditional logic and just support the version of liger in the container?

File: bin/batch_correction_liger.Rmd [hunk 2]
```diff
@@ -53,9 +53,15 @@ so[["RNA"]] <- as(so[["RNA"]], Class = "Assay5")
 if ("counts" %in% Layers(so)) {
   so[["RNA"]] <- split(so[["RNA"]], f = so$Sample)
 }
+#set reduction name based on version of rliger
+reduction_label <- "inmfNorm"
+if(packageVersion("rliger") < "2.0"){
+  reduction_label <- "iNMF"
+}
```
Comment (kelly-sovacool) [inline bin/batch_correction_liger.Rmd:60]: are we sure we want to support version of rliger < 2.0? see also https://github.com/CCBR/SINCLAIR/pull/228/changes#r3140231109

**Review by kelly-sovacool — CHANGES_REQUESTED** [review]
I think it's worth considering only supporting rliger >= 2.0 since we control the version available in the container. It'll make this code simpler.

File: bin/scRNA_functions.R (hunk 1 above)
Comment (wong-nw) [reply bin/scRNA_functions.R:267]: More in the vein of keeping it just in case the container needs to be isolated and the Biowulf package repo is the primary. We should be able to remove the condition when we've completely severed the local Biowulf dependency

Comment (kelly-sovacool) [reply bin/scRNA_functions.R:267]: @wong-nw we already are severing the dependency on biowulf modules in the containerize branch. Do you anticipate possible needing to roll back the liger version in the container? that would be the main reason to keep it.

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,7 @@
 - Creates cache for celldex reference downloads in working directory (#203, @wong-nw)
 - Set main job memory to 2 GB for slurm mode. (#205, @kelly-sovacool)
 - Checks for joined RNA "layers" in Seurat v5 object (#224, @wong-nw)
+- Updates to code to match latest version of `rliger` (#228, @wong-nw)
```
Comment (kelly-sovacool) [inline CHANGELOG.md]:
```suggestion
- Support `rliger` versions < 2.0 and >= 2.0. (#228, @wong-nw)
```

**Comment by kelly-sovacool** [comment]
after discussion in MS Teams, we decided to keep the code as-is to maintain backwards compatibility in case we need to roll back the version of rliger in the container
